---
- name: "Lighthouse : install dependencies"
  ansible.builtin.dnf:
    state: present
    name:
      - git
      - nginx

- name: "Lighthouse : clone repository"
  ansible.builtin.git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    dest: /opt/lighthouse

- name: "Lighthouse : configure nginx"
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf

- name: "Lighthouse : start nginx"
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
